---
- name: "set http_proxy fact"
  set_fact:
    http_proxy: "{{ squid_proxy_host }}:{{ squid_proxy_port }}"

- name: "redhat disable fastmirror"
  lineinfile:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: 'enabled=1'
    line: 'enabled=0'
  when: ansible_pkg_mgr == "yum"

- name: "redhat config yum proxy"
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: "^proxy=*"
    insertafter: EOF
    line: "proxy={{ http_proxy }}"
  ignore_errors: yes
  when: ansible_pkg_mgr == "yum"

- name: "config apt caching"
  template:
    src: "01proxy.j2"
    dest: "{{ squid_apt_conf_file }}"
    owner: root
    group: root
    mode: 0644
  when: ansible_pkg_mgr == "apt"

# TODO add system wide proxy.sh